### ISSUE TITLE
Move distribution bundle to `dist` folder, build test bundle separately.

### ISSUE THREAD

**Issue by jamestalmage** [power-assert-js/espower#22]
It is annoying to have `git status` constantly return that `build/espower.js` is `not staged for commit`.

I agree build artifacts should not be checked in with every commit, but it should be easier to avoid.

@twada - I am not sure what you use to automate deploys. But I find [`cut-release`](https://www.npmjs.com/package/cut-release) and npm [`preversion`/`version`](https://github.com/npm/npm/issues/8620) scripts to be the simplest.

**Comment by twada** [comment]
Currently, I don't want to change output destination of artifacts to `dist` now, because many front-end developers are using the filepath via bower (and npm). It's a breaking change.

However, output automation to `build` and git ignore it makes sense and,

> npm preversion/version scripts

That's so cool!

I'm going to refactor my release process.

**Comment by jamestalmage** [comment]
> output automation to build and git ignore it

I've tried that before and it doesn't work. `git commit -a` still picks up .gitignored files if they are already added to your git cache. If it ever did work, then you'd be stuck `--force` adding anytime you did want to make a change.

> I don't want to change output destination of artifacts to `dist`

OK, that makes sense. What if we just point all the artifacts created during tests to `temp-build`, and only update `dist` in the `version` script.

**Comment by twada** [comment]
> What if we just point all the artifacts created during tests to `temp-build`, and only update `dist` in the `version` script.

Yes I think so too.

**Comment by twada** [comment]
Close this issue since espower@65c5713 has landed.

refs: [chore(espower): prefer local build to make tests less annoying](https://github.com/power-assert-js/espower/commit/65c5713c7e831e9c929ad657847b7b6d55e2ae3b)
